---
title: "Multiple Regression R Notebook"
output: html_notebook
---

Start up.

```{r}
rm(list = ls()) # Clear all
graphics.off() # Close all
cat("\014") # Clear console
```

Here's the data.

```{r}
mouse.data <- data.frame(
  size = c(1.4, 2.6, 1.0, 3.7, 5.5, 3.2, 3.0, 4.9, 6.3),
  weight = c(0.9, 1.8, 2.4, 3.5, 3.9, 4.4, 5.1, 5.6, 6.3),
  tail = c(0.7, 1.3, 0.7, 2.0, 3.6, 3.0, 2.9, 3.9, 4.0))

mouse.data
```
Reviewing simple regression by modeling mouse size with mouse weight.

STEP 1: Draw a graph of the data to make sure the relationship make sense:

```{r}
plot(mouse.data$weight, mouse.data$size, pch=16, cex=2)
```
STEP 2: Do the regression

```{r}
simple.regression <- lm(size ~ weight, data=mouse.data)
```

STEP 3: Look at the R^2, F-value and p-value

```{r}
summary(simple.regression)

```
```{r}
plot(mouse.data$weight, mouse.data$size, pch=16, cex=2)
abline(simple.regression, lwd=5, col="red")
```

Now let's verify that our formula for R^2 is correct..

```{r}
ss.mean <- sum((mouse.data$size - mean(mouse.data$size))^2)
ss.simple <- sum(simple.regression$residuals^2)

(ss.mean - ss.simple) / ss.mean # this is the R^2 value

## now let's verify the our formula for F is correct...
f.simple <- ((ss.mean - ss.simple) / (2 - 1)) / 
  (ss.simple / (nrow(mouse.data) - 2))

f.simple # this is the F-value

## Now let's draw a figure that shows how to calculate the p-value from the
## F-value
##
## First, draw the correct f-distribution curve with df1=1 and df2=7
x <- seq(from=0, to=15, by=0.1)
y <- df(x, df1=1, df2=7)
plot(x, y, type="l")
```

